name: sendCurl

# Run workflow on commits to default branch
on: 
  
  workflow_dispatch :
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CURL-ACTION
        # You may pin to the exact commit or the version.
        run: |
          # curl arguments
          curl -v --user ${{ secrets.MAVEN_USERNAME }}:${{ secrets.MAVEN_PASSWORD }} --url https://oss.sonatype.org/content/repositories/snapshots/com/adobe/campaign/tests/log-parser/
      
          
